title: prodbee
email: p13tarunkk@iima.ac.in
description: >-
  Bees are one of one of the most creative living species. But this one is
  virtual !
baseurl: ''
url: ''
twitter_username: ''
github_username: ''
theme: minima
plugins:
  - jekyll-feed
  - ''
