name: Prodbee
description: >-
  The beehive of product management. Insights on how Digital Product Managers
  solve business and customer problems to drive growth and sustainability
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: ''
url: 'https://prodbee.com'
disqus: prodbee
email: p13tarunkk@iima.ac.in
mailchimp-list: null
include:
  - _pages
permalink: '/:title/'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
authors:
  tarun:
    name: Tarun
    site: 'https://www.tarunk.com'
    avatar: assets/images/avatar1.jpg
    bio: >-
      <b>Creator & Consultant</b> @ Prodbee <br> <b>Product Professional</b> @
      Amazon | Ex - Target, Lazada (Alibaba group), Magicbricks (Times Group), 
      Ola Cabs   <br> <b>Enthusiast</b> @ Photography | Arts | Web-designing |
      Boxing
    email: p13tarunkk@iima.ac.in
    twitter: 'https://twitter.com/theprodbee'
    linkedin: 'https://www.linkedin.com/in/tarun-product/'
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: tarun
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: _pages
    values:
      layout: page
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
