# Site
name: 'Prodbee'
description: 'The beehive of product management. Insights on how Digital Product Managers solve business and customer problems to drive growth and sustainability'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: "https://prodbee.com"
disqus: 'prodbee'
email: 'p13tarunkk@iima.ac.in'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  tarun:
    name:           Tarun
    site:           https://www.linkedin.com/in/tarun-k-900a71115
    avatar:         assets/images/avatar1.jpg
    bio:            "<b>Creator & Consultant</b> @ Prodbee <br> <b>Product Professional</b> @ Lazada, Alibaba group | Magicbricks, Times Group (Ex) | Ola Cabs (Ex) <br> <b>Enthusiast</b> @ Photography | Arts | Web-designing | Boxing"
    email:          p13tarunkk@iima.ac.in
    twitter:        
    linkedin:       https://www.linkedin.com/in/tarun-k-900a71115

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: tarun
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]